version: "3"
PostgreSQL:
  restart: always
  image: sameersbn/postgresql:9.5-3
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=user
    - DB_PASS=batatinha1234
    - DB_NAME=lojinha_do_matheus
    - DB_TEMPLATE=

    - DB_EXTENSION=

    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=false
  volumes:
    - ./data:/var/lib/postgresql
