# v3.5 syntax
version: '3.5'

# Named volumes
volumes:
  # MySQL Data
  laravel_project-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: laravel_project-mysql
    volumes:
      - laravel_project-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=laravel_project
      - MYSQL_DATABASE=laravel_project
      - MYSQL_USER=laravel_project
      - MYSQL_PASSWORD=laravel_project

  # php:7.2-nginx
  app:
    image: ambientum/php:7.2-nginx
    container_name: laravel_project-app
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    links:
      - mysql
      