version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mf
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
    volumes:
      - ./data/db:/var/lib/mysql

  dump:
    build: Dumper/
    volumes:
      - ./Dumper/:/var/db/
    command: sh -c "sleep 20 && /usr/bin/mysql -h mysql -uroot -proot < /var/db/mftrading.sql"
    depends_on:
      - db

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html/wp-content/themes/mftrading
    restart: always
    environment:
      WORDPRESS_DB_HOST: 3333
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
#    volumes:
#      db_data:
