# v3.3 syntax
version: '3.3'

# Named volumes
volumes:
  # MySQL Data
  blog-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: blog-mysql
    volumes:
      - blog-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=blog
      - MYSQL_DATABASE=blog
      - MYSQL_USER=blog
      - MYSQL_PASSWORD=blog

  # PHP 7.1-apache
  app:
    image: ambientum/php:7.1-apache
    container_name: blog-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - mysql
